'use strict';

const PDFKit = require('pdfkit');
const { v4: uuidv4 } = require('uuid');
const { getDb } = require('../db/connection');

/**
 * Generate a receipt number: DB-[PROP_CODE]-[YYYYMM]-[SEQ]
 * e.g. DB-PRIYA-202601-0042
 */
function generateReceiptNumber(db, propertyId, billingMonth) {
  const prop = db.prepare('SELECT property_code FROM properties WHERE id = ?').get(propertyId);
  const code = (prop?.property_code || 'PROP').toUpperCase();
  const ym   = (billingMonth || new Date().toISOString().substring(0, 7)).replace('-', '');

  const last = db.prepare(`
    SELECT receipt_number FROM receipts
    WHERE property_id = ? AND receipt_number LIKE ?
    ORDER BY created_at DESC LIMIT 1
  `).get(propertyId, `DB-${code}-${ym}-%`);

  let seq = 1;
  if (last) {
    const parts = last.receipt_number.split('-');
    seq = parseInt(parts[parts.length - 1], 10) + 1;
  }

  return `DB-${code}-${ym}-${String(seq).padStart(4, '0')}`;
}

/**
 * Create a receipt record for a payment ledger entry.
 * Returns the created receipt object or null if already exists.
 */
async function generateReceipt({ db: passedDb, paymentId, propertyId, residentId, actorId }) {
  const db = passedDb || getDb();

  const existing = db.prepare('SELECT * FROM receipts WHERE payment_ledger_id = ?').get(paymentId);
  if (existing) return existing;

  const payment = db.prepare('SELECT * FROM payment_ledger WHERE id = ?').get(paymentId);
  if (!payment) return null;

  const resident = db.prepare('SELECT full_name, mobile FROM residents WHERE id = ?').get(residentId);
  const receiptNumber = generateReceiptNumber(db, propertyId, payment.billing_month);

  const lineItems = [
    {
      description: `${payment.type.replace('_', ' ')} — ${payment.billing_month || 'N/A'}`,
      amount_paise: payment.amount_paise,
    },
  ];

  const id  = uuidv4();
  const now = new Date().toISOString();
  db.prepare(`
    INSERT INTO receipts
      (id, property_id, resident_id, payment_ledger_id, receipt_number,
       amount_paise, line_items, wa_delivered, created_at)
    VALUES (?, ?, ?, ?, ?, ?, ?, 0, ?)
  `).run(id, propertyId, residentId, paymentId, receiptNumber,
    payment.amount_paise, JSON.stringify(lineItems), now);

  return db.prepare('SELECT * FROM receipts WHERE id = ?').get(id);
}

/**
 * Generate a PDF buffer for a receipt.
 */
async function generateReceiptPdf(receipt) {
  return new Promise((resolve, reject) => {
    try {
      const doc    = new PDFKit({ size: [226, 500], margin: 16 }); // 80mm thermal
      const chunks = [];
      doc.on('data', c => chunks.push(c));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const lineItems = typeof receipt.line_items === 'string'
        ? JSON.parse(receipt.line_items) : receipt.line_items || [];

      doc.fontSize(12).font('Helvetica-Bold').text(receipt.property_name || 'DormBook', { align: 'center' });
      doc.fontSize(8).font('Helvetica').text(receipt.property_address || '', { align: 'center' });
      doc.moveDown(0.5);
      doc.fontSize(10).font('Helvetica-Bold').text('PAYMENT RECEIPT', { align: 'center' });
      doc.moveTo(16, doc.y).lineTo(210, doc.y).stroke();
      doc.moveDown(0.3);
      doc.fontSize(8).font('Helvetica');
      doc.text(`Receipt No: ${receipt.receipt_number}`);
      doc.text(`Date: ${new Date(receipt.created_at).toLocaleDateString('en-IN')}`);
      doc.text(`Resident: ${receipt.resident_name}`);
      doc.text(`Mobile: ${receipt.resident_mobile}`);
      doc.moveDown(0.5);
      doc.moveTo(16, doc.y).lineTo(210, doc.y).stroke();
      doc.moveDown(0.3);

      lineItems.forEach(item => {
        doc.text(item.description, { continued: true });
        doc.text(`₹${(item.amount_paise / 100).toFixed(2)}`, { align: 'right' });
      });

      doc.moveDown(0.3);
      doc.moveTo(16, doc.y).lineTo(210, doc.y).stroke();
      doc.moveDown(0.3);
      doc.fontSize(9).font('Helvetica-Bold');
      doc.text('TOTAL', { continued: true });
      doc.text(`₹${(receipt.amount_paise / 100).toFixed(2)}`, { align: 'right' });
      doc.moveDown(0.5);
      doc.fontSize(7).font('Helvetica').text('Thank you for your payment.', { align: 'center' });
      doc.text('Generated by DormBook', { align: 'center' });
      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

module.exports = { generateReceipt, generateReceiptPdf, generateReceiptNumber };
